/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as ManadensArtikelRouteImport } from './routes/manadens-artikel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFeedRouteImport } from './routes/api/feed'

const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const ManadensArtikelRoute = ManadensArtikelRouteImport.update({
  id: '/manadens-artikel',
  path: '/manadens-artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manadens-artikel': typeof ManadensArtikelRoute
  '/statistik': typeof StatistikRoute
  '/api/feed': typeof ApiFeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manadens-artikel': typeof ManadensArtikelRoute
  '/statistik': typeof StatistikRoute
  '/api/feed': typeof ApiFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manadens-artikel': typeof ManadensArtikelRoute
  '/statistik': typeof StatistikRoute
  '/api/feed': typeof ApiFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manadens-artikel' | '/statistik' | '/api/feed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manadens-artikel' | '/statistik' | '/api/feed'
  id: '__root__' | '/' | '/manadens-artikel' | '/statistik' | '/api/feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManadensArtikelRoute: typeof ManadensArtikelRoute
  StatistikRoute: typeof StatistikRoute
  ApiFeedRoute: typeof ApiFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manadens-artikel': {
      id: '/manadens-artikel'
      path: '/manadens-artikel'
      fullPath: '/manadens-artikel'
      preLoaderRoute: typeof ManadensArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManadensArtikelRoute: ManadensArtikelRoute,
  StatistikRoute: StatistikRoute,
  ApiFeedRoute: ApiFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
